### ISSUE TITLE
Moriah workflow failed processing a frame System.TypeInitializationException

### ISSUE THREAD

**Issue by dacoppet** [Microsoft/Gestures-Samples#11]
Whenever I launch the Microsoft  Gestures Service I always get the following error and Can't use the app nor the framework at all. Please seet the full details below:

1.  [2017/07/13 10:31:10.065] [WorkflowManager] Trying to setup workflow [Intel(R) RealSense(TM) Camera SR300 Depth]->[MapleRapidDataProcessor]->[SimpleGestureDetector]...

2. [2017/07/13 10:31:11.386] [WorkflowManager] Workflow loaded successfully [Intel(R) RealSense(TM) Camera SR300 Depth]->[MapleRapidDataProcessor]->[SimpleGestureDetector]...

3. [2017/07/13 10:31:11.818] [WorkflowManager] Failed processing frame: Moriah workflow failed processing a frame System.TypeInitializationException: The type initializer for 'Microsoft.MSR.ATL.ATLI.Moriah.MapleSkeleton' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.MSR.ATL.ATLI.Moriah.HandSkeleton.SkeletonBase' threw an exception. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'string' to 'float'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.MSR.ATL.ATLI.Moriah.HandSkeleton.SatisfactionParameters..ctor(Object parameters)
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.MSR.ATL.ATLI.Moriah.HandSkeleton.SkeletonBase..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.MSR.ATL.ATLI.Moriah.HandSkeleton.SkeletonBase.OverrideSatisfactionParameters(Object overridingConfig)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.MSR.ATL.ATLI.Moriah.MapleSkeleton..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.MSR.ATL.ATLI.Moriah.MapleSkeleton..ctor(MapleEstimation mapleEstimation)
   at Microsoft.MSR.ATL.ATLI.Moriah.Runtime.Workflow.SensorDataProcessors.Maple.MapleRapidDataProcessor.<>c.<ActualProcessFrame>b__13_2(MapleEstimation est)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.MSR.ATL.ATLI.Moriah.Runtime.Workflow.SensorDataProcessors.Maple.MapleRapidDataProcessor.ActualProcessFrame(SensorFrame frame)
   at Microsoft.Gestures.Runtime.Workflow.Manager.DataModel.WorkflowElementBase`2.ProcessFrame(InputFrameType inputFrame)
   at Microsoft.Gestures.Runtime.Workflow.Manager.WorkflowWorker.DoWorkflowIteration()
   at Microsoft.Gestures.Runtime.Workflow.Manager.WorkflowWorker.TryWorkflowIteration()

**Comment by kfirkarmon** [comment]
Can't seem to reproduce this on our machines. Do you still encounter this issue?

**Comment by dupuyjs** [comment]
Same issue/call stack with Kinect sensor v2. Any idea ?

[2017/09/25 14:59:17.450] [WorkflowManager] Failed processing frame: Moriah workflow failed processing a frame System.TypeInitializationException: The type initializer for 'Microsoft.MSR.ATL.ATLI.Moriah.MapleSkeleton' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.MSR.ATL.ATLI.Moriah.HandSkeleton.SkeletonBase' threw an exception. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'string' to 'float'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.MSR.ATL.ATLI.Moriah.HandSkeleton.SatisfactionParameters..ctor(Object parameters)
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.MSR.ATL.ATLI.Moriah.HandSkeleton.SkeletonBase..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.MSR.ATL.ATLI.Moriah.HandSkeleton.SkeletonBase.OverrideSatisfactionParameters(Object overridingConfig)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.MSR.ATL.ATLI.Moriah.MapleSkeleton..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.MSR.ATL.ATLI.Moriah.MapleSkeleton..ctor(MapleEstimation mapleEstimation)
   at Microsoft.MSR.ATL.ATLI.Moriah.Runtime.Workflow.SensorDataProcessors.Maple.MapleRapidDataProcessor.<>c.<ActualProcessFrame>b__14_2(MapleEstimation est)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.MSR.ATL.ATLI.Moriah.Runtime.Workflow.SensorDataProcessors.Maple.MapleRapidDataProcessor.ActualProcessFrame(SensorFrame frame)
   at Microsoft.Gestures.Runtime.Workflow.Manager.DataModel.WorkflowElementBase`2.ProcessFrame(InputFrameType inputFrame)
   at Microsoft.Gestures.Runtime.Workflow.Manager.WorkflowWorker.DoWorkflowIteration()
   at Microsoft.Gestures.Runtime.Workflow.Manager.WorkflowWorker.TryWorkflowIteration()

**Comment by YoniSmolin** [comment]
@dacoppet @dupuyjs 

Guys, we've pushed an update that will hopefully fix your issue. Please run the Microsoft Gestures Service and verify that you have the latest version (1.0.17337.1):

![image](https://user-images.githubusercontent.com/11846732/33543845-39dd5130-d8e1-11e7-8f35-9db2f053c7c1.png)

Please let us know if the issue keeps recurring. Unfortunately, we haven't been able to reproduce it locally...

**Comment by mosdav** [comment]
Solved, starting from, **1.0.17337.1** drop/build
