### ISSUE TITLE
Cannot parse "1.0" to its numeric equivalent

### ISSUE THREAD

**Issue by taszilvo** [Microsoft/Gestures-Samples#25]
Hi.

Can you help me guys to fix this? Please! Thanks!

~~~
[2018.06.13 11:31:10.239] [WorkflowManager] Failed processing frame: Moriah workflow failed processing a frame System.TypeInitializationException: The type initializer for 'Microsoft.MSR.ATL.ATLI.Moriah.MapleSkeleton' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.MSR.ATL.ATLI.Moriah.HandSkeleton.SkeletonBase' threw an exception. ---> Microsoft.Gestures.GesturesFrameworkObjectValidationException: Invalid value assigned to [value]:
Cannot parse "1.0" to its numeric equivalent
   at Microsoft.MSR.ATL.ATLI.Moriah.HandSkeleton.SatisfactionParameters.ParseToNumeric[T](Object value)
   at CallSite.Target(Closure , CallSite , SatisfactionParameters , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.MSR.ATL.ATLI.Moriah.HandSkeleton.SatisfactionParameters..ctor(Object parameters)
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.MSR.ATL.ATLI.Moriah.HandSkeleton.SkeletonBase..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.MSR.ATL.ATLI.Moriah.HandSkeleton.SkeletonBase.OverrideSatisfactionParameters(Object overridingConfig)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.MSR.ATL.ATLI.Moriah.MapleSkeleton..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.MSR.ATL.ATLI.Moriah.MapleSkeleton..ctor(MapleEstimation mapleEstimation)
   at Microsoft.MSR.ATL.ATLI.Moriah.Runtime.Workflow.SensorDataProcessors.Maple.MapleRapidDataProcessor.<>c.<ActualProcessFrame>b__14_2(MapleEstimation est)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.MSR.ATL.ATLI.Moriah.Runtime.Workflow.SensorDataProcessors.Maple.MapleRapidDataProcessor.ActualProcessFrame(SensorFrame frame)
   at Microsoft.Gestures.Runtime.Workflow.Manager.DataModel.WorkflowElementBase`2.ProcessFrame(InputFrameType inputFrame)
   at Microsoft.Gestures.Runtime.Workflow.Manager.WorkflowWorker.DoWorkflowIteration()
   at Microsoft.Gestures.Runtime.Workflow.Manager.WorkflowWorker.TryWorkflowIteration()
~~~

**Comment by taszilvo** [comment]
We solved it. We had to change deep windows setting for double values. Use 1.0 instead of 1,0.
