### ISSUE TITLE
Intel RealSense SR305

### ISSUE THREAD

**Issue by dzoech** [microsoft/Gestures-Samples#31]
Since I was not able to purchase an SR300 camera, I am trying to use Project Gesture with the successor model SR305. 

Unfortunately, the Gesture Service doesn't look like it would support it as it throws the following exception:

```
[2020-03-04 12:22:49.011] [WorkflowManager] Workflow not loaded: Microsoft.Gestures.Runtime.Workflow.Manager.Exceptions.InvalidWorkflowException: None of the preconfigured workflows loaded successfully
	None of the preconfigured sensors loaded successfully
	Sensor plug-in Intel(R) RealSense(TM) Camera SR300 Depth is disconnected or failed to initialize.
	Sensor plug-in Intel(R) RealSense(TM) Camera SR300 Depth is disconnected or failed to initialize.
	Sensor plug-in Intel(R) RealSense(TM) Camera SR300 Depth is disconnected or failed to initialize.
	Sensor plug-in Intel(R) RealSense(TM) Camera SR300 Depth is disconnected or failed to initialize.
	None of the preconfigured sensors loaded successfully
	Sensor plug-in Intel(R) RealSense(TM) 410 Depth is disconnected or failed to initialize.
	Sensor plug-in Intel(R) RealSense(TM) 410 Depth is disconnected or failed to initialize.
	None of the preconfigured sensors loaded successfully
	Sensor plug-in WDF KinectSensor Interface 0 is disconnected or failed to initialize.
	Sensor plug-in WDF KinectSensor Interface 0 is disconnected or failed to initialize.
	None of the preconfigured sensors loaded successfully
	Sensor plug-in Intel(R) RealSense(TM) 3D Camera (Front F200) Depth is disconnected or failed to initialize.
	Sensor plug-in Intel(R) RealSense(TM) 3D Camera (Front F200) Depth is disconnected or failed to initialize. ---> System.AggregateException: One or more errors occurred. ---> Microsoft.Gestures.Runtime.Workflow.Manager.Exceptions.InvalidWorkflowException: None of the preconfigured sensors loaded successfully
	Sensor plug-in Intel(R) RealSense(TM) Camera SR300 Depth is disconnected or failed to initialize.
	Sensor plug-in Intel(R) RealSense(TM) Camera SR300 Depth is disconnected or failed to initialize.
	Sensor plug-in Intel(R) RealSense(TM) Camera SR300 Depth is disconnected or failed to initialize.
	Sensor plug-in Intel(R) RealSense(TM) Camera SR300 Depth is disconnected or failed to initialize. ---> System.AggregateException: One or more errors occurred. ---> Microsoft.Gestures.Runtime.Workflow.Manager.Exceptions.InvalidWorkflowException: Sensor plug-in Intel(R) RealSense(TM) Camera SR300 Depth is disconnected or failed to initialize.
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.Gestures.Runtime.Workflow.Manager.WorkflowLoader.SpecificWorkflowConfigurationLoad(String sensorFriendlyName, String sensorDataProcessorFriendlyName, String gestureDetectorFriendlyName, Object dynamicConfig, IAvailableWorkflowElements availableWorkflowElements, IDeviceManagerListener deviceManagerListener, TryingToSetupWorkflowEventHandler handler)
   at Microsoft.Gestures.Runtime.Workflow.Manager.WorkflowLoader.Load(IEnumerable`1 configurations, Object dynamicConfig, IAvailableWorkflowElements availableWorkflowElements, IDeviceManagerListener deviceManagerListener, TryingToSetupWorkflowEventHandler handler)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.Gestures.Runtime.Workflow.Manager.WorkflowLoader.Load(IEnumerable`1 configurations, Object dynamicConfig, IAvailableWorkflowElements availableWorkflowElements, IDeviceManagerListener deviceManagerListener, TryingToSetupWorkflowEventHandler handler)
   at Microsoft.Gestures.Runtime.Workflow.Manager.WorkflowLoader.<>c__DisplayClass4_0.<LoadAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at Microsoft.Gestures.Runtime.Workflow.Manager.WorkflowManager.<InitializeWorkflow>d__86.MoveNext()
```

Is this by design or am I doing something wrong in setting up the camera?

**Comment by YoniSmolin** [comment]
@dzoech, we currently only support the [listed models](https://docs.microsoft.com/en-us/gestures/#supported-depth-cameras). SR305 is not in the list. We currently have no plans to expand this list.

**Comment by dzoech** [comment]
@YoniSmolin Thanks for the quick reply.

I'm aware of that list. According to Intel the SR305 is just the same camera as the SR300 but with a different case. Therefore, I think there should be no technical limitations. 

Is there a way to test if the SR305 works? As it seems the list of "functioning" models is hard-coded in your library.

**Comment by YoniSmolin** [comment]
I don't see any reason it shouldn't work but, as you say, the list of supported sensors is indeed hard-coded and, regretfully, we plan no new releases in the upcoming future.

**Comment by dzoech** [comment]
Since I'm not very proficient with the project gesture library nor the SR300/5 could you give me a hint how I might accomplish enabling the SR305? Like, how are you checking what sensor/camera is connected?

Moreover, am I correct in the assumption that the library's source code is not open-source?

**Comment by YoniSmolin** [comment]
You are correct, the source code is not open. Unfortunately, I don't see an easy way to add support for a new sensor without access to the code.

You might be able to hack your way to some of the configurations in the compiled code (%USERPROFILE%\AppData\Roaming\Microsoft\Prague\PragueVersions\LatestVersion), but this is a long shot...

**Comment by dzoech** [comment]
Ok, thank you, I see what I can do :)
